export const shipModelPaths = {
    cargoShip01: './models/cargo_ship_01.glb',
    cargoShip02: './models/cargo_ship_02.glb',
    cargoShip03: './models/cargo_ship_03.glb',
    cargoShip04Empty: './models/cargo_ship_04_empty.glb',
    craneShip01: './models/crane_ship_01.glb',
    tugBoat01: './models/tug_boat_01.glb',
    tugBoat02: './models/tug_boat_02.glb',
    tugBoat03: './models/tug_boat_03.glb'
};

export const shipsData = [
    {
        id: 'atlantic-trader',
        name: 'ATLANTIC TRADER',
        shipType: 'cargoShip02',
        type: 'Cargo Ship',
        category: 'Cargo',
        company: 'Atlantic Maritime',
        imo: '1234567',
        mmsi: '987654321',
        flag: 'Liberia',
        flagImage: './images/flags/lr.png',
        trailColor: 0xff9f1c,
        destination: 'Dakar, Senegal',
        eta: 'May 17, 08:30',
        speed: '10.4 kn',
        course: '190.2°',
        draught: '8.7 m',
        status: 'Under way',
        callsign: 'EABC2',
        lengthBeam: '160 / 25 m',
        scale: 16,
        moveSpeed: 0.07,
        turnSpeed: 0.0003,
        forwardOffset: Math.PI / 2,
        startPosition: { x: 200, y: 11, z: 400 }
    },
    {
        id: 'porto-fiscardo',
        name: 'PORTO FISCARDO',
        shipType: 'cargoShip01',
        type: 'Bulk Carrier',
        category: 'Bulk Carrier',
        company: 'Fiscardo Shipping',
        imo: '9643219',
        mmsi: '354837000',
        flag: 'Panama',
        flagImage: './images/flags/pa.png',
        trailColor: 0x00d4ff,
        destination: 'Las Palmas, Spain',
        eta: 'May 15, 17:00',
        speed: '8.9 kn',
        course: '28.7°',
        draught: '11.3 m',
        status: 'Under way',
        callsign: '3EEE7',
        lengthBeam: '190 / 32 m',
        scale: 1.6,
        moveSpeed: 0.06,
        turnSpeed: 0.00032,
        trailOffsetMultiplier: 0.05,
        forwardOffset: -Math.PI / 2,
        startPosition: { x: 0, y: 0, z: 0 }
    },
    {
        id: 'ocean-mariner',
        name: 'OCEAN MARINER',
        shipType: 'cargoShip03',
        type: 'Bulk Carrier',
        category: 'Bulk Carrier',
        company: 'Oceanic Lines',
        imo: '9384721',
        mmsi: '256734000',
        flag: 'Malta',
        flagImage: './images/flags/mt.png',
        trailColor: 0xff4d6d,
        destination: 'Rotterdam, Netherlands',
        eta: 'May 18, 14:20',
        speed: '11.2 kn',
        course: '34.6°',
        draught: '10.9 m',
        status: 'Under way',
        callsign: '9HXM8',
        lengthBeam: '185 / 31 m',
        scale: 18,
        moveSpeed: 0.075,
        turnSpeed: 0.00028,
        forwardOffset: Math.PI / 2,
        startPosition: { x: -180, y: 9, z: 140 }
    },

    {
        id: 'canary-star',
        name: 'CANARY STAR',
        shipType: 'cargoShip04Empty',
        type: 'Container Ship',
        category: 'Container',
        company: 'Canary Star Logistics',
        imo: '9475832',
        mmsi: '224918000',
        flag: 'Marshall Islands',
        flagImage: './images/flags/mh.png',
        trailColor: 0x57cc99,
        destination: 'Santa Cruz de Tenerife, Spain',
        eta: 'May 16, 09:45',
        speed: '13.6 kn',
        course: '76.3°',
        draught: '9.4 m',
        status: 'Under way',
        callsign: 'ECKS4',
        lengthBeam: '210 / 32 m',
        scale: 8,
        moveSpeed: 0.09,
        turnSpeed: 0.00026,
        forwardOffset: Math.PI / 2,
        startPosition: { x: 200, y: 4.5, z: 160 }
    },

    {
        id: 'harbor-star',
        name: 'HARBOR STAR',
        shipType: 'craneShip01',
        type: 'Crane Ship',
        category: 'Crane',
        company: 'Atlantic Maritime',
        imo: '9582041',
        mmsi: '371420000',
        flag: 'Bahamas',
        flagImage: './images/flags/bs.png',
        trailColor: 0xffd60a,
        destination: 'Port of Las Palmas',
        eta: 'May 15, 11:30',
        speed: '6.2 kn',
        course: '92.4°',
        draught: '5.8 m',
        status: 'Restricted manoeuvrability',
        callsign: '3FJC9',
        lengthBeam: '92 / 24 m',
        scale: 5,
        moveSpeed: 0.045,
        turnSpeed: 0.0004,
        forwardOffset: -Math.PI / 2,
        startPosition: { x: -120, y: -4, z: -160 }
    },

    {
        id: 'tug-atlas',
        name: 'TUG ATLAS',
        shipType: 'tugBoat01',
        type: 'Tug Boat',
        category: 'Tug',
        company: 'Atlas Towage',
        imo: '9812456',
        mmsi: '224673000',
        flag: 'Spain',
        flagImage: './images/flags/es.png',
        trailColor: 0x9b5de5,
        destination: 'Harbor Operations',
        eta: 'In port',
        speed: '4.8 kn',
        course: '145.7°',
        draught: '3.2 m',
        status: 'Under way',
        callsign: 'ECTG5',
        lengthBeam: '32 / 10 m',
        scale: 2,
        moveSpeed: 0.08,
        turnSpeed: 0.00075,
        forwardOffset: 0,
        startPosition: { x: 80, y: -2, z: 220 }
    },

    {
        id: 'tug-orion',
        name: 'TUG ORION',
        shipType: 'tugBoat02',
        type: 'Tug Boat',
        category: 'Tug',
        company: 'Orion Towage',
        imo: '9827365',
        mmsi: '256882000',
        flag: 'Singapore',
        flagImage: './images/flags/sg.png',
        trailColor: 0xf15bb5,
        destination: 'Towage Area Alpha',
        eta: 'May 15, 13:10',
        speed: '5.5 kn',
        course: '208.9°',
        draught: '3.5 m',
        status: 'Under way',
        callsign: '9HRO2',
        lengthBeam: '34 / 11 m',
        scale: 2,
        moveSpeed: 0.09,
        turnSpeed: 0.00075,
        forwardOffset: 0,
        startPosition: { x: -230, y: -1, z: 40 }
    },

    {
        id: 'tug-neptune',
        name: 'TUG NEPTUNE',
        shipType: 'tugBoat03',
        type: 'Tug Boat',
        category: 'Tug',
        company: 'Neptune Harbor Services',
        imo: '9831942',
        mmsi: '257904000',
        flag: 'Norway',
        flagImage: './images/flags/no.png',
        trailColor: 0x70e000,
        destination: 'Pilot Station',
        eta: 'May 15, 18:45',
        speed: '7.1 kn',
        course: '12.6°',
        draught: '3.1 m',
        status: 'Under way',
        callsign: 'LNTU8',
        lengthBeam: '30 / 9 m',
        scale: 2,
        moveSpeed: 0.105,
        turnSpeed: 0.0008,
        forwardOffset: 0,
        startPosition: { x: 240, y: -1.3, z: -210 }
    }
];
